### ISSUE TITLE
issues running terrascan

### ISSUE THREAD

**Issue by j-rat** [cesar-rodriguez/terrascan#4]
I am having a hard time just testing terrascan.  I am very interested in playing with it, but can't quite get the built in unittests to run successfully.  Thoughts?

``[jrat@centos7 terrascan]$ python -m unittest tests.test_logging_and_monitoring.TestLoggingAndMonitoring``

``Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_logging_and_monitoring'
[jrat@centos7 terrascan]$ vi terrascan/test_logging_and_monitoring.py``

**Comment by cesar-rodriguez** [comment]
Seems like I renamed the original tests folder to terrascan. I updated the readme with the correct instructions. Let me know if that fixes the issue.

**Comment by j-rat** [comment]
I'm not sure if I am doing something wrong or not, but it still doesn't run successfully.  :(
